// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
)

type Channel struct {
	TeamID  string          `json:"team_id"`
	ID      string          `json:"id"`
	Name    string          `json:"name"`
	Type    string          `json:"type"`
	Unread  int64           `json:"unread"`
	Updated int64           `json:"updated"`
	Members json.RawMessage `json:"members"`
	Topic   json.RawMessage `json:"topic"`
}

type Message struct {
	TeamID    string          `json:"team_id"`
	ChannelID string          `json:"channel_id"`
	Ts        string          `json:"ts"`
	User      sql.NullString  `json:"user"`
	Text      sql.NullString  `json:"text"`
	ThreadTs  sql.NullString  `json:"thread_ts"`
	Blocks    json.RawMessage `json:"blocks"`
	Raw       json.RawMessage `json:"raw"`
}
