// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
)

const getMeta = `-- name: GetMeta :one
SELECT value FROM meta WHERE key = ?
`

func (q *Queries) GetMeta(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getMeta, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getMinChannelUpdated = `-- name: GetMinChannelUpdated :one
SELECT CAST(COALESCE(MAX(updated), 0) AS INTEGER) FROM channels WHERE team_id = ?
`

func (q *Queries) GetMinChannelUpdated(ctx context.Context, teamID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getMinChannelUpdated, teamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listChannels = `-- name: ListChannels :many
SELECT team_id, id, name, type, unread, mentions, updated, members, topic FROM channels
WHERE team_id = ? AND type = ? ORDER BY name
`

type ListChannelsParams struct {
	TeamID string `json:"team_id"`
	Type   string `json:"type"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.TeamID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Unread,
			&i.Mentions,
			&i.Updated,
			&i.Members,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIms = `-- name: ListIms :many
SELECT team_id, id, user, unreads, updated FROM ims
WHERE team_id = ? ORDER BY user
`

func (q *Queries) ListIms(ctx context.Context, teamID string) ([]Im, error) {
	rows, err := q.db.QueryContext(ctx, listIms, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Im
	for rows.Next() {
		var i Im
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.User,
			&i.Unreads,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT team_id, channel_id, ts, user, text, thread_ts, blocks, raw FROM messages
WHERE team_id = ? AND channel_id = ? ORDER BY ts DESC LIMIT ?
`

type ListMessagesParams struct {
	TeamID    string `json:"team_id"`
	ChannelID string `json:"channel_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessages, arg.TeamID, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.TeamID,
			&i.ChannelID,
			&i.Ts,
			&i.User,
			&i.Text,
			&i.ThreadTs,
			&i.Blocks,
			&i.Raw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannel = `-- name: UpsertChannel :exec
INSERT INTO channels (team_id, id, name, type, unread, mentions, updated, members, topic)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (team_id, id) DO UPDATE SET
  name = excluded.name, type = excluded.type,
  unread = excluded.unread, updated = excluded.updated,
  members = excluded.members, topic = excluded.topic
`

type UpsertChannelParams struct {
	TeamID   string          `json:"team_id"`
	ID       string          `json:"id"`
	Name     string          `json:"name"`
	Type     string          `json:"type"`
	Unread   int64           `json:"unread"`
	Mentions int64           `json:"mentions"`
	Updated  int64           `json:"updated"`
	Members  json.RawMessage `json:"members"`
	Topic    json.RawMessage `json:"topic"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.TeamID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Unread,
		arg.Mentions,
		arg.Updated,
		arg.Members,
		arg.Topic,
	)
	return err
}

const upsertIm = `-- name: UpsertIm :exec
INSERT INTO ims (team_id, id, user, unreads, updated)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (team_id, id) DO UPDATE SET
  user = excluded.user, unreads = excluded.unreads, updated = excluded.updated
`

type UpsertImParams struct {
	TeamID  string `json:"team_id"`
	ID      string `json:"id"`
	User    string `json:"user"`
	Unreads int64  `json:"unreads"`
	Updated int64  `json:"updated"`
}

func (q *Queries) UpsertIm(ctx context.Context, arg UpsertImParams) error {
	_, err := q.db.ExecContext(ctx, upsertIm,
		arg.TeamID,
		arg.ID,
		arg.User,
		arg.Unreads,
		arg.Updated,
	)
	return err
}

const upsertMessage = `-- name: UpsertMessage :exec
INSERT INTO messages (team_id, channel_id, ts, user, text, thread_ts, blocks, raw)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (team_id, channel_id, ts) DO UPDATE SET
  user = excluded.user, text = excluded.text, thread_ts = excluded.thread_ts,
  blocks = excluded.blocks, raw = excluded.raw
`

type UpsertMessageParams struct {
	TeamID    string          `json:"team_id"`
	ChannelID string          `json:"channel_id"`
	Ts        string          `json:"ts"`
	User      sql.NullString  `json:"user"`
	Text      sql.NullString  `json:"text"`
	ThreadTs  sql.NullString  `json:"thread_ts"`
	Blocks    json.RawMessage `json:"blocks"`
	Raw       json.RawMessage `json:"raw"`
}

func (q *Queries) UpsertMessage(ctx context.Context, arg UpsertMessageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMessage,
		arg.TeamID,
		arg.ChannelID,
		arg.Ts,
		arg.User,
		arg.Text,
		arg.ThreadTs,
		arg.Blocks,
		arg.Raw,
	)
	return err
}

const upsertMeta = `-- name: UpsertMeta :exec
INSERT INTO meta (key, value) VALUES (?, ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

type UpsertMetaParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertMeta(ctx context.Context, arg UpsertMetaParams) error {
	_, err := q.db.ExecContext(ctx, upsertMeta, arg.Key, arg.Value)
	return err
}
