// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"encoding/json"
)

const listChannels = `-- name: ListChannels :many
SELECT team_id, id, name, type, unread, updated, members, topic FROM channels
WHERE team_id = ? AND type = ? ORDER BY name
`

type ListChannelsParams struct {
	TeamID string `json:"team_id"`
	Type   string `json:"type"`
}

func (q *Queries) ListChannels(ctx context.Context, arg ListChannelsParams) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, arg.TeamID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.TeamID,
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Unread,
			&i.Updated,
			&i.Members,
			&i.Topic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minChannelUpdated = `-- name: MinChannelUpdated :one
SELECT CAST(COALESCE(MAX(updated), 0) AS INTEGER) FROM channels WHERE team_id = ?
`

func (q *Queries) MinChannelUpdated(ctx context.Context, teamID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, minChannelUpdated, teamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const upsertChannel = `-- name: UpsertChannel :exec
INSERT INTO channels (team_id, id, name, type, unread, updated, members, topic)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (team_id, id) DO UPDATE SET
  name = excluded.name, type = excluded.type,
  unread = excluded.unread, updated = excluded.updated,
  members = excluded.members, topic = excluded.topic
`

type UpsertChannelParams struct {
	TeamID  string          `json:"team_id"`
	ID      string          `json:"id"`
	Name    string          `json:"name"`
	Type    string          `json:"type"`
	Unread  int64           `json:"unread"`
	Updated int64           `json:"updated"`
	Members json.RawMessage `json:"members"`
	Topic   json.RawMessage `json:"topic"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannel,
		arg.TeamID,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Unread,
		arg.Updated,
		arg.Members,
		arg.Topic,
	)
	return err
}
