name: build for macos arm64

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: set up go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.1"

      - name: build & sign
        run: make build-mac

      - name: compress
        run: zip -r hammock-macos-arm64.zip Hammock.app

      - name: upload file
        uses: actions/upload-artifact@v7
        with:
          name: hammock-macos-arm64
          path: hammock-macos-arm64.zip
